import chalk from 'chalk'
import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { listSnapshots, loadSnapshot } from '../store/snapshots.js'
import type { Snapshot } from '../types.js'

const SUPPORTED = ['brewfile', 'bootstrap'] as const
type ExportFormat = typeof SUPPORTED[number]

function generateBrewfile(snapshot: Snapshot): string {
  if (!snapshot.brew.data) return '# No Homebrew data in snapshot\n'
  const { formulae, casks } = snapshot.brew.data
  const lines: string[] = ['# Generated by devsnap', `# Snapshot: ${snapshot.id}`, '']
  if (formulae.length > 0) {
    lines.push('# Formulae')
    formulae.forEach((f) => lines.push(`brew "${f.name}"`))
    lines.push('')
  }
  if (casks.length > 0) {
    lines.push('# Casks')
    casks.forEach((c) => lines.push(`cask "${c.name}"`))
    lines.push('')
  }
  return lines.join('\n')
}

function generateBootstrap(snapshot: Snapshot): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Bootstrap script generated by devsnap',
    `# Snapshot: ${snapshot.id}`,
    '# Run: bash bootstrap.sh',
    '',
    'set -euo pipefail',
    '',
  ]

  // Homebrew
  lines.push('# ── Homebrew ─────────────────────────────────────────────────────────────')
  lines.push('if ! command -v brew &>/dev/null; then')
  lines.push('  echo "Installing Homebrew..."')
  lines.push('  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"')
  lines.push('fi')
  lines.push('')

  if (snapshot.brew.data?.formulae.length) {
    lines.push('echo "Installing Homebrew formulae..."')
    snapshot.brew.data.formulae.forEach((f) => lines.push(`brew install "${f.name}" 2>/dev/null || true`))
    lines.push('')
  }

  if (snapshot.brew.data?.casks.length) {
    lines.push('echo "Installing Homebrew casks..."')
    snapshot.brew.data.casks.forEach((c) => lines.push(`brew install --cask "${c.name}" 2>/dev/null || true`))
    lines.push('')
  }

  // Node
  if (snapshot.node.data) {
    const n = snapshot.node.data
    lines.push('# ── Node ─────────────────────────────────────────────────────────────────')
    lines.push(`# Node ${n.nodeVersion} detected`)
    if (n.nvmVersion) {
      lines.push('# nvm detected — install via: https://github.com/nvm-sh/nvm')
      lines.push(`# nvm install ${n.nodeVersion}`)
    }
    if (n.pnpmVersion) lines.push(`npm install -g "pnpm@${n.pnpmVersion}" 2>/dev/null || true`)
    if (n.bunVersion) lines.push(`# bun ${n.bunVersion} — install via: https://bun.sh`)
    if (n.globalPackages.length > 0) {
      lines.push('echo "Installing global npm packages..."')
      n.globalPackages
        .filter((p) => p.version)
        .forEach((p) => lines.push(`npm install -g "${p.name}@${p.version}" 2>/dev/null || true`))
    }
    lines.push('')
  }

  // CLI tools
  if (snapshot.cliTools.data) {
    const installed = snapshot.cliTools.data.tools.filter((t) => t.installed && t.name !== 'git' && t.name !== 'curl')
    if (installed.length > 0) {
      lines.push('# ── CLI Tools ────────────────────────────────────────────────────────────')
      lines.push('echo "Installing CLI tools via brew..."')
      installed.forEach((t) => lines.push(`brew install "${t.name}" 2>/dev/null || true`))
      lines.push('')
    }
  }

  lines.push('echo "Bootstrap complete!"')
  return lines.join('\n')
}

export async function runExport(format: string, outputPath?: string): Promise<void> {
  if (!(SUPPORTED as readonly string[]).includes(format)) {
    console.error(`Unknown export format: ${format}. Supported: ${SUPPORTED.join(', ')}`)
    process.exit(1)
  }

  const snapshots = await listSnapshots()
  if (snapshots.length === 0) {
    console.error('No snapshots found. Run `devsnap scan` first.')
    process.exit(1)
  }

  const latest = snapshots[snapshots.length - 1]
  let snapshot
  try {
    snapshot = await loadSnapshot(latest.id)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error(msg)
    process.exit(1)
  }

  const fmt = format as ExportFormat

  if (fmt === 'brewfile') {
    const content = generateBrewfile(snapshot)
    const dest = outputPath ? resolve(outputPath) : resolve('Brewfile')
    await writeFile(dest, content, 'utf8')
    console.log(chalk.green('Brewfile written → ') + dest)
    console.log(chalk.dim(`  ${snapshot.brew.data?.formulae.length ?? 0} formulae, ${snapshot.brew.data?.casks.length ?? 0} casks`))
  } else if (fmt === 'bootstrap') {
    const content = generateBootstrap(snapshot)
    const dest = outputPath ? resolve(outputPath) : resolve('bootstrap.sh')
    await writeFile(dest, content, { encoding: 'utf8', mode: 0o755 })
    console.log(chalk.green('Bootstrap script written → ') + dest)
    console.log(chalk.dim('  Run with: bash bootstrap.sh'))
  }
}
